### ISSUE TITLE
Labs do not correspond to the training structure

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365#1]
The structure of the labs is definitely not compliant with the structure of the already published training content:

1. Following labs for the module 1: "Module 1, Lab 1 – Data Modeling, Module 1, Lab 2 – Model driven app, Module 1, Lab 3 – Canvas app" all require MB-200 skills, which are not covered at all in the module 1 of the MB-400 course
2. Following labs for the module 2: "Module 2, Lab 1 – Client scripting, Module 2, Lab 2 – PowerApps Component Framework" are NOT covered in module 2 but rather in module 3
3. Moreover the whole topic of PowerApps Component Framework is covered in the last lesson of the module 3 with just few sentences, without any details necessary for understanding the topic and being able to perform the lab.
4. Following lab for module 2; "Module 2, Lab 4 – Azure Functions" is not covered in the whole training MB-400 at all.
5. Following labs for the module 3: "Module 3, Lab 1 – Publishing events externally, Module 3, Lab 2 – Custom connectors, Module 3, Lab 3 – Application Lifecycle Management" are not covered in the whole training MB-400 at all.

**Comment by skulthm-ms** [comment]
Thank you Robert. You are right about most of these notes. We just pushed some edits to the lab but we still have gaps as you mentioned which we are addressing in the new PL-400 course where MB-200 no longer a prerequisite.
