### ISSUE TITLE
Module 2 Lab 2 Can't resolve 'moment'

### ISSUE THREAD

**Issue by LukeDuffy98** [MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365#10]
# Module: 02
#### Step: 12

Description of issue

Repro steps:

1. Follow lab steps
2. Get to run command : npm run build and the following output appears. Happens in newly built vm ans well as Lab Provider machines

C:\Users\lukeadmin\Documents\pcfTimelineControl\src>npm run build

> pcf-project@1.0.0 build C:\Users\lukeadmin\Documents\pcfTimelineControl\src
> pcf-scripts build

[0:21:59] [build]  Initializing...
[0:21:59] [build]  Validating manifest...
[0:21:59] [build]  Validating control...
[0:22:2] [build]  Generating manifest types...
[0:22:2] [build]  Compiling and bundling control...
[Webpack stats]:
Hash: f1d604ed9102a71e682b
Version: webpack 4.42.1
Time: 7414ms
Built at: 07/15/2020 12:22:10 AM
    Asset     Size  Chunks             Chunk Names
bundle.js  543 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[./node_modules/vis-timeline/peer/umd/vis-timeline-graph2d.min.js] 512 KiB {main} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 475 bytes {main} [built]
[./timelinecontrol/index.ts] 3.37 KiB {main} [built]

ERROR in ./node_modules/vis-timeline/peer/umd/vis-timeline-graph2d.min.js
Module not found: Error: Can't resolve 'moment' in 'C:\Users\lukeadmin\Documents\pcfTimelineControl\src\node_modules\vis-timeline\peer\umd'
 @ ./node_modules/vis-timeline/peer/umd/vis-timeline-graph2d.min.js 27:74-91
 @ ./timelinecontrol/index.ts

ERROR in ./node_modules/vis-timeline/peer/umd/vis-timeline-graph2d.min.js
Module not found: Error: Can't resolve 'vis-data/peer/umd/vis-data.js' in 'C:\Users\lukeadmin\Documents\pcfTimelineControl\src\node_modules\vis-timeline\peer\umd'
 @ ./node_modules/vis-timeline/peer/umd/vis-timeline-graph2d.min.js 27:93-133
 @ ./timelinecontrol/index.ts
[0:22:10] [build]  Failed:
[pcf-1033] [Error] An error occurred compiling or bundling the control.

**Comment by megha1810** [comment]
Module 2, Lab 2  Exercie1 Step 7 Task 4 : Error 


ERROR in ./node_modules/vis-timeline/peer/umd/vis-timeline-graph2d.min.js
Module not found: Error: Can't resolve 'vis-data/peer/umd/vis-data.js' in 'C:\Users\azureuser\Documents\pcfTimelineControl\src\node_modules\vis-timeline\peer\umd'
 @ ./node_modules/vis-timeline/peer/umd/vis-timeline-graph2d.min.js 27:93-133
 @ ./timelinecontrol/index.ts
[19:24:39] [start] [watch] Failed:
[pcf-1033] [Error] An error occurred compiling or bundling the control

**Comment by skulthm-ms** [comment]
Thank you for reporting these issues. We just updated the labs and you no longer should get these errors.
