### ISSUE TITLE
Missing images, lab files

### ISSUE THREAD

**Issue by RobertRybaric** [MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365#2]
In preparation for the training delivery I started to work through the labs. The lab guidances are correct and correspond to the latest product features, however, the files mentioned in the labs are missing. I was able to work through:
Module 1, Lab 1 – Data Modeling - no issues found

Module 1, Lab 2 - Model driven app - in the Task #1: Edit Permit Form and View, step 9. Add Build Site lookup, Contact lookup, Start Date and New Size to the form. The form should now look like the image below -> there is no "image below"

Module 1, Lab 3 – Data Modeling (wrong name anyway, should be "Canvas app") - in the Task #1: Create Canvas App, step 5. Import Component. -> there should be 3 components imported from a "lab resources folder", however, there is nothing like this folder with the components,

So this stopped me from being able to continue to execute the labs. Please ensure ALL FILES NEEDED FOR THE LABS ARE UPLOADED HERE!!!!!!!!!!!!!

**Comment by anjenni** [comment]
Hi Robert! Our apologies - we missed uploading that resource. The resources should now be available in the Allfiles tab of the GitHub repo. Please let us know if you have any more comments. Appreciate the feedback.
