### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by megha1810** [MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365#4]
# Module: 1
#### Step: 3

Description of issue
InspectionList.Selected.'Inspection (contoso_inspection)'

Name isnt't valid.This identifier is not recognized.

![Mb-400 Error](https://user-images.githubusercontent.com/43968741/79204328-02f52c80-7e5a-11ea-9cda-14172d722104.png)

**Comment by skulthm-ms** [comment]
Thank you for reporting these issues. We just updated the labs and you no longer should get these errors.
