### ISSUE TITLE
Error:  Parent.Height - (DetailsHeader.Height\*2)

### ISSUE THREAD

**Issue by megha1810** [MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365#5]
# Module: 1
#### Step: 4

Description of issue
Resize the Edit form as

5th bullet Point Number 3.  

Select **Height** property and set it to the formula below.  
Parent.Height - (DetailsHeader.Height \*2)
In formula append '/' before * 2 as given in lab.It is not taking '/' in issue box.

Throwing error on writing above code.

working fine if Changed it to Parent.Height - (DetailsHeader.Height / 2)
Is this what expected?

**Comment by skulthm-ms** [comment]
Thank you for reporting these issues. We just updated the labs and you no longer should get these errors.
