### ISSUE TITLE
Deprecated Client Scripting

### ISSUE THREAD

**Issue by ariclevin** [MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365#6]
# Module: 2
#### Task: 2, Step 5

Usage of deprecated Xrm.Page instead of formContext:
In the steps above of task 1 and 2 , the instruction specify the following code:

- Xrm.Page.ui.tabs.get("inspectionsTab").setVisible(false);

instead of 

- formContext.ui.tabs.get("inspectionsTab").setVisible(false);

#### Task: 1, Step 5

Usage of deprecated Xrm.Page instead of formContext:
In Step 5 of the task listed above, the instruction specify the following code:

-   Xrm.Page.getAttribute("contoso_newsize").setRequiredLevel("none");
-   Xrm.Page.getAttribute("contoso_newsize").setRequiredLevel("required");
-   Xrm.Page.ui.controls.get("contoso_newsize").setVisible(true);
-   Xrm.Page.ui.controls.get("contoso_newsize").setVisible(false);

instead of 

-   formContext.getAttribute("contoso_newsize").setRequiredLevel("none");
-   formContext.getAttribute("contoso_newsize").setRequiredLevel("required");
-   formContext.getControl("contoso_newsize").setVisible(true);
-   formContext.getControl("contoso_newsize").setVisible(false);

#### Task: 3, Step 6

Usage of deprecated Xrm.Page instead of formContext:
In the above task and step the the instruction specify to use:

- var PermitID = Xrm.Page.data.entity.getId().replace('{', '').replace('}', '');

which is deprecated instead of 

- var PermitID = formContext.data.entity.getId().replace('{', '').replace('}', '');

#### Task: 3, Step 8

Usage of deprecated Xrm.Page instead of formContext:
In the above task and step the the instruction specify to use:

- Xrm.Page.ui.setFormNotification("Status " + result.status, "INFORMATION");

which is deprecated instead of 

- formContext.ui.setFormNotification("Status " + result.status, "INFORMATION");

**Comment by skulthm-ms** [comment]
Thank you for reporting these issues. We just updated the labs and you no longer should get these errors.
