### ISSUE TITLE
Missing Files/Images

### ISSUE THREAD

**Issue by ariclevin** [MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365#7]
# Module: 2
#### Task: 1, Step 4

Create test record

- Go back to the **Permit Management** application.
- Select **Inspections**.
- You should have two inspections one **Failed** and one **Passed**. If not, open them and update the records.
- Click **New**.
- Provide the information shown in the image below and click **Save**.
- Click **New** again.
- Provide the information shown in the image below and click **Save**.

In the above step, no images are available for:
Provide the information shown in the image below and click **Save**

The current step can therefore not be completed. Nothing is available in Allfiles folder eihter.

**Comment by skulthm-ms** [comment]
Thank you for reporting these issues. We just updated the labs and you no longer should get these errors.
