### ISSUE TITLE
Documentation referring to classic Azure Portal and needs to be updated

### ISSUE THREAD

**Issue by ariclevin** [MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365#8]
# Module: 3
#### Step: 1

Documentation seems to be referring to Old Azure Portal
When creating a new resource of type function, there are additional details that have to be entered:

- Runtime stack
- Version
- Region

#### Step: 1

Documentation seems to be referring to Old Azure Portal
InPortal and Webhook + API are not available in the modern Azure Interface, only in the Classic one.
New Function template include: HTTP Trigger, Timer Trigger, Azure Service Bus Triggers, Azure Event Hub Triggers, etc...

Either the documentation should provide instructions to switch to classic experience (Overview -> Switch to classic experience -> Continue to classic experience) or be updated to have instructions for new interface/commands.

**Comment by skulthm-ms** [comment]
Thank you for reporting these issues. We just updated the labs and you no longer should get these errors.
