### ISSUE TITLE
MB-400 MODULE 3 LAB 3

### ISSUE THREAD

**Issue by james-elfred** [MicrosoftLearning/MB-400-Microsoft-PowerApps-Dynamics-365#9]
# Module: 03
#### Step: 00

Description of issue
The only still valid part of this lab is how to create a devops account. The rest of the lab refers to old an version of devops in the instructions.

**Comment by skulthm-ms** [comment]
Thank you for reporting these issues. We just updated the labs and you no longer should get these errors.
